### Numpy

- convert A list,tuple,dict in to Numpy array
- How to generate array with in a range of values arange
- linspace
- random.randint
- basic arthimetc operators on numpy array

In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# slicing 
print(a[1:10])
print(a[1:5:2])
print(a[:])

[1 2 3 4 5 6 7 8 9]
[1 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
# Fancy Indexing or Boolean Indexing
print(a[a>5])

[6 7 8 9]


In [5]:
a.shape

(10,)

In [6]:
a.ndim

1

In [7]:
a2 = np.random.randint(10,30,(3,3))
a2

array([[11, 10, 15],
       [27, 21, 24],
       [28, 18, 28]])

In [8]:
print(a2.ndim)
print(a2.shape)

2
(3, 3)


In [9]:
for i in a2:
    print(i)
    break

[11 10 15]


In [7]:
import numpy as np
a2 = np.random.randint(10,30,(3,3))
a2

array([[27, 22, 27],
       [11, 21, 21],
       [16, 10, 12]])

In [10]:
print(a2)

[[11 10 15]
 [27 21 24]
 [28 18 28]]


In [9]:
for i in a2:
    for j in i:
        print(j,end=' ')
    print()

27 22 27 
11 21 21 
16 10 12 


In [10]:
print(a2[0],type(a2[0]),a2[0].shape)

[27 22 27] <class 'numpy.ndarray'> (3,)


In [11]:
print(a2[1:],type(a2[1:].shape))

[[11 21 21]
 [16 10 12]] <class 'tuple'>


In [12]:
# rows ffrom 0 to 2
# columns frm 0 to 2
# 1st row and 2nd row
print(a2[1][2])
print(a2[1,2])

21
21


In [13]:
print(a2[1:3,0:2])

[[11 21]
 [16 10]]


In [14]:
print(a2[1:3])

[[11 21 21]
 [16 10 12]]


In [15]:
print(a2)

[[27 22 27]
 [11 21 21]
 [16 10 12]]


In [17]:
a3 = np.random.randint(10,100,(5,5,3))
a3

array([[[53, 93, 28],
        [61, 28, 99],
        [11, 90, 60],
        [60, 27, 91],
        [34, 42, 12]],

       [[96, 20, 31],
        [12, 84, 73],
        [83, 36, 19],
        [30, 18, 74],
        [56, 97, 44]],

       [[91, 64, 67],
        [97, 61, 16],
        [30, 79, 73],
        [57, 83, 22],
        [67, 34, 46]],

       [[92, 79, 60],
        [60, 61, 85],
        [14, 29, 84],
        [85, 52, 78],
        [24, 73, 86]],

       [[43, 86, 23],
        [68, 72, 44],
        [42, 13, 28],
        [33, 81, 10],
        [24, 94, 80]]])

In [18]:
print(a3[1::2])

[[[96 20 31]
  [12 84 73]
  [83 36 19]
  [30 18 74]
  [56 97 44]]

 [[92 79 60]
  [60 61 85]
  [14 29 84]
  [85 52 78]
  [24 73 86]]]


In [19]:
print(a3[:2])

[[[53 93 28]
  [61 28 99]
  [11 90 60]
  [60 27 91]
  [34 42 12]]

 [[96 20 31]
  [12 84 73]
  [83 36 19]
  [30 18 74]
  [56 97 44]]]


In [21]:
print(a3[1::2,2])

[[83 36 19]
 [14 29 84]]


In [22]:
a3==86

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False,  True]],

       [[False,  True, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [23]:
# Boolean Indexing
a3[a3==86]

array([86, 86])

In [24]:
a3[a3>50]

array([53, 93, 61, 99, 90, 60, 60, 91, 96, 84, 73, 83, 74, 56, 97, 91, 64,
       67, 97, 61, 79, 73, 57, 83, 67, 92, 79, 60, 60, 61, 85, 84, 85, 52,
       78, 73, 86, 86, 68, 72, 81, 94, 80])

In [25]:
a3[(a3>50) & (a3<70)] # or -- |

array([53, 61, 60, 60, 56, 64, 67, 61, 57, 67, 60, 60, 61, 52, 68])

In [26]:
a3[(a3<50) | (a3>70)]

array([93, 28, 28, 99, 11, 90, 27, 91, 34, 42, 12, 96, 20, 31, 12, 84, 73,
       83, 36, 19, 30, 18, 74, 97, 44, 91, 97, 16, 30, 79, 73, 83, 22, 34,
       46, 92, 79, 85, 14, 29, 84, 85, 78, 24, 73, 86, 43, 86, 23, 72, 44,
       42, 13, 28, 33, 81, 10, 24, 94, 80])

In [27]:
L = list(range(100))
# 0,1,2,3,4---L[:]
# 1,2,3,4....L[1:]
# 1,3,5,7,9---L[1::2]
# 1,13,45,74,23,67---

In [28]:
aL = np.array(L)
aL[[1,13,45,74,23,67]]

array([ 1, 13, 45, 74, 23, 67])

In [29]:
aL[[45,67,89,1,2,34]]

array([45, 67, 89,  1,  2, 34])

In [30]:
a2

array([[27, 22, 27],
       [11, 21, 21],
       [16, 10, 12]])

In [31]:
a2[[1,2],[0,1]]

array([11, 10])

In [34]:
print(a3[[1,2],[1,2],[1,2]])
print(a3[1,1,1])
print(a3[2,2,2])

[84 73]
84
73


### Stastical Functions

In [41]:
a = np.random.randint(20,30,5)
a

array([22, 24, 28, 26, 27])

In [42]:
print(np.mean(a))# avg
print(np.sum(a)/np.size(a))

25.4
25.4


In [44]:
np.median(a)# sorting

26.0

In [45]:
print(np.quantile(a,0.5))# q2
print(np.quantile(a,0.25))# q1
print(np.quantile(a,0.75))# q3

26.0
24.0
27.0


### Logerthemic and Exponential

In [46]:
np.log(2) # log with base e

0.6931471805599453

In [47]:
np.log2(2)

1.0

In [48]:
print(np.log(np.exp(1)))

1.0


In [49]:
print(np.log10(5))

0.6989700043360189


In [50]:
np.log(0)

C:\Users\Kiranmai\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [51]:
np.exp(1)

2.718281828459045

In [52]:
np.exp(2)

7.38905609893065

In [53]:
print(np.exp2(4)) #2**4

16.0


In [54]:
print(np.expm1(2)) # np.exp(2)-1

6.38905609893065


In [55]:
print(np.exp(2)-1)

6.38905609893065
