* Classifiation 
    - Binary classification
    - Multiclass
    - Sentiment Analysis
    - Anomly detection
* Regression
* Recommender system
* Reinforcement learning
* NLP
    - Q&A
    - Auto completion
    - chatbot
* Computer Vision
    - Object detection
    - Object tracking
    - Image classification
    - Image tagging
* Data
    - Numerical data
    - Image data
    - Audio data
    - Vedio data
    - Text data
    - from documents
    - Satelite imagery
    - Time series data(temperature regarding,stock prices)

Supervised machine learning is a type of machine learning algorithm that uses a known dataset which is recognized as the training dataset to make predictions
Supervised learning includes two categories of algorithms: regression and classification algorithms. There’s a significant difference between the two:
Regression models are used to predict a continuous value. Predicting prices of a house given the features of house like size, price etc 

In [2]:
#### what is supervised learning?
#### unsupervised learning ?
#### reinforcement learning ?
#### coloborative filtering and content based filtering?
#### deep learning - NLP Natural language processing, computer vision


#### What are csv, tsv files?
    - Tab Separated Values (TSV)and Comma Separated Values (CSV) are the two file type extensions used to load a set of data. A . tsv file will have tab separated values whereas . csv file has comma separated fields. These types of files are used to get raw data for many purposes possible.
#### What are packages available to handle csv data?
    - 
#### What is json format?
#### How to handle json data?
#### What are packages available for image data?
#### What are the packages available for audio data?
#### With all the packages above check how to read the data?
#### How to display the same data?

Replace comma in the file sample.csv with tab and store it in a file a tsv format.
- i/p : A csv file
- o/p : Is a tsv file with same data
    - Step 1 : Read the data using open
    - Step 2 : Replace comma with tab
    - Step 3 : Write the data into file with extension tsv
- Packages to handle csv data
    - Pandas
    - CSV
    - NumPy

In [4]:
out = [5,69,11,13,2,8,9,6]

In [5]:
# replace the multiples of 3 with -1
out1 = [i if i%3 != 0 else -1 for i in out]
out1

[5, -1, 11, 13, 2, 8, -1, -1]

In [6]:
out.extend([2,3,4,56])

In [7]:
out

[5, 69, 11, 13, 2, 8, 9, 6, 2, 3, 4, 56]

In [9]:
# replace multiples of 2 with -2
# replace multiples of 3 with -1
# it it is multiples of both replace it with -2

out1 = []
for i in out:
    if i % 2 == 0:
        out1.append(-2)
    elif i % 3 == 0:
        out1.append(-1)
    else:
        out1.append(i)
print(out1)
print(out)
out2 = [-2 if i % 2 == 0 else -1 if i % 3 == 0 else i for i in out]
print(out2)

[5, -1, 11, 13, -2, -2, -1, -2, -2, -1, -2, -2]
[5, 69, 11, 13, 2, 8, 9, 6, 2, 3, 4, 56]
[5, -1, 11, 13, -2, -2, -1, -2, -2, -1, -2, -2]


#### List comprehension with nested for

In [12]:
l1 = [3,8,5,67,3]
l2 = [1,2,3,4,5]

In [15]:
num = [(i,j) for i  in l1 for j in l2]
print(num,end = ' ')

[(3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (67, 1), (67, 2), (67, 3), (67, 4), (67, 5), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5)] 

In [28]:
l2 = [[2,3],[3,4],[4,5]]
x = [j for i in l2 for j in i]
x

[2, 3, 3, 4, 4, 5]

In [24]:
# common elements in two lists using list comprehension
l3 = list(range(5,10,2))
l4 = list(range(1,10,2))
print(l3,l4)

[5, 7, 9] [1, 3, 5, 7, 9]


In [26]:
y = [i for i in l3 for j in l4 if i==j]
y

[5, 7, 9]

### NumPy
- Numberical python
- Vectorized programming
- Handling multidimensional data
- Manipulating Arrays
- We can define the data type
- Commonly used with numerical data. But you may use mixed data as well
- Faster Execution
- Less Memory
- Most of the mathematical functions are availble
    - Linear Algebra
    - 

In [29]:
# version 
import numpy 
numpy.__version__ # attribute '__' - dunder

'1.16.5'

In [30]:
import numpy as np

#### Converting existing data into numpy array

In [31]:
l = [3,4,5,66,7]
array_1d = np.array(l)
print(type(array_1d))
print(array_1d)

<class 'numpy.ndarray'>
[ 3  4  5 66  7]


In [32]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [33]:
t = (5,6,7,8,9)
array_1d = np.array(t)
print(type(array_1d))
print(array_1d)

<class 'numpy.ndarray'>
[5 6 7 8 9]


In [34]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [35]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [36]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### Creating Arrays with in a specific range