#### Import numpy as np and print the version number.

In [1]:
import numpy as np
np.__version__

'1.16.5'

#### Create a 1D array of numbers from 0 to 9

In [3]:
print(np.arange(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create a 3×3 numpy array of all True’s

In [6]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
np.zeros((3,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

#### Extract all odd numbers from arr

In [11]:
l=np.arange(20)
print(l)
print(type(l))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [12]:
for i in l:
    if i%2!=0:
        print(i)
    else:
        pass

1
3
5
7
9
11
13
15
17
19


#### Replace all odd numbers in arr with -1

In [15]:
for i in l:
    if i%2!=0:
        l[i]=-1
    else:
        pass
print(l)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


#### Convert a 1D array to a 2D array with 2 rows

In [28]:
a=np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [33]:
b=np.reshape(a,(2,-1))
print(b)
np.ndim(b)

[[1 2 3 4]
 [5 6 7 8]]


2

#### Stack arrays a and b vertically

In [36]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [39]:
np.vstack(a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
np.vstack(b)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### Stack the arrays a and b horizontally.

In [41]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [42]:
np.hstack(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.hstack(b)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Get the positions where elements of a and b match

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


In [59]:
for i in range(len(a)):
    if a[i]==b[i]:
        print(i,end=" ")

1 3 5 7 

#### Get all items between 5 and 10 from a.

In [61]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)

[ 2  6  1  9 10  3 27]


In [62]:
for i in a:
    if i>5 and i<10:
        print(i)

6
9


#### Write a NumPy program to generate five random numbers from the normal distribution

In [66]:
a=np.random.normal(size=5) # from normal distribution 
print(a)

[-0.13363446  2.53249259 -0.39133614  0.36109166 -0.13381642]


#### Write a NumPy program to generate six random integers between 10 and 30

In [69]:
b=np.random.randint(10,30,size=6)
print(b)

[11 17 29 24 12 16]


#### Write a NumPy program to create a 3x3x3 array with random values

In [70]:
x=np.random.random((3,3,3))
print(x)

[[[0.76925593 0.85125788 0.58259888]
  [0.45028003 0.3654279  0.39427728]
  [0.72719329 0.80148096 0.50273964]]

 [[0.34788725 0.73786053 0.89974055]
  [0.59127869 0.81658756 0.78639123]
  [0.86653016 0.32433035 0.63190556]]

 [[0.25108342 0.17595839 0.80945098]
  [0.92342517 0.9550194  0.61898066]
  [0.34341151 0.85975942 0.71627666]]]


#### Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [75]:
s=np.random.random((5,5))
print(s)

[[0.53931088 0.0081624  0.20026964 0.74545119 0.93298825]
 [0.82358689 0.63826718 0.03938453 0.17917989 0.84554452]
 [0.98285585 0.62942255 0.66314801 0.36615963 0.66809082]
 [0.09542718 0.19107957 0.89193712 0.69591338 0.66071956]
 [0.98747842 0.19196818 0.01004005 0.67893152 0.04998645]]


In [76]:
np.max(s)

0.9874784161127674

In [77]:
np.min(s)

0.008162398868479692

#### Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [79]:
a=np.random.random((10,4))
print(a)

[[0.47477707 0.15896401 0.34835235 0.55485352]
 [0.904954   0.77477005 0.94198087 0.66435013]
 [0.0391545  0.12978313 0.10730143 0.79798378]
 [0.64676319 0.6030269  0.4316578  0.73573048]
 [0.22246503 0.33438994 0.80891365 0.41074502]
 [0.83682446 0.42287706 0.8074849  0.85235979]
 [0.45339461 0.16127785 0.26414692 0.39715721]
 [0.43161947 0.6006933  0.89132219 0.56601911]
 [0.6651877  0.60624818 0.10579295 0.81654882]
 [0.3572609  0.45656526 0.65282917 0.7408458 ]]


In [84]:
h=a[0:5,:]
print(h)

[[0.47477707 0.15896401 0.34835235 0.55485352]
 [0.904954   0.77477005 0.94198087 0.66435013]
 [0.0391545  0.12978313 0.10730143 0.79798378]
 [0.64676319 0.6030269  0.4316578  0.73573048]
 [0.22246503 0.33438994 0.80891365 0.41074502]]


#### Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [92]:
x = np.arange(10)
print(x)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[5 1 3 2 6 0 9 8 7 4]


#### Read an JPEG image into a numpy array, return the size and shap of that image

In [101]:
from PIL import Image # pillow module
from numpy import asarray # converting image to array
image = Image.open('kolala.jpg')
data = asarray(image)
print(type(data))
print(data.shape)
print(data.size)

<class 'numpy.ndarray'>
(413, 550, 3)
681450


In [ ]:
Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

#### swap columns 1 and 2 in the array arr.

In [106]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[0,1]]=arr[:,[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### How to reverse the rows of a 2D array?

In [108]:
arr = np.arange(9).reshape(3,3)
print(arr)
np.flip(arr,axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### Reverse the columns of a 2D array arr.

In [113]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr.T


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])